name: "Build & Deploy"

on: [push]

jobs:
  testing:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: pytest
      - run: black --line-length 120 --check --diff -l 120 **/*.py
  image:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [image, testing]
    runs-on: [self-hosted, Linux]
    env:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0
      TF_VAR_github_token: ${{ secrets.GHCR_TOKEN }}
      TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
      TF_VAR_sentry_dsn: ${{ secrets.SENTRY_DSN }}
      TF_VAR_ping_url: ${{ secrets.PING_URL }}
      TF_VAR_commit: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.2
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
    environment:
      name: production
      url: https://wbld.app
